name = "The Weave: A New Beginning"
author = "Pahsunaal"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ac292b7ca98a5f0d3024e27819df4681848b00fa6261366eb7daed51cf5fd6b4"

[versions]
fabric = "0.15.7"
minecraft = "1.20.4"

[options]
datapack-folder = "config/openloader/data"
